services:
  flask:
    image: ghcr.io/gabrielgst/esa-analytics-flask:latest
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file:
      - flask/.env
    environment:
      FLASK_HOST: "0.0.0.0"
    volumes:
      - esa_analytics_db:/app/flask/instance
      - esa_analytics_tmp:/app/flask/tmp
    restart: unless-stopped

  nextjs:
    image: ghcr.io/gabrielgst/esa-analytics-nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    env_file:
      - .env.local
    environment:
      FLASK_INTERNAL_URL: "http://flask:5050"
    ports:
      - "5010:5000"
    depends_on:
      - flask
    restart: unless-stopped

volumes:
  esa_analytics_db:
  esa_analytics_tmp:
