"""Added impact to the activity model

Revision ID: 1c9ca6f81c35
Revises: ec02de294910
Create Date: 2025-09-08 15:34:16.514531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9ca6f81c35'
down_revision = 'ec02de294910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('impact2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('impact3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('impact3')
        batch_op.drop_column('impact2')
        batch_op.drop_column('impact1')

    # ### end Alembic commands ###
