"""Corrected childActivities column definition

Revision ID: 7c2264eb7c09
Revises: ecad0f2362a1
Create Date: 2025-09-07 14:11:40.964562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2264eb7c09'
down_revision = 'ecad0f2362a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('childActivities', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('childActivities')

    # ### end Alembic commands ###
