"""Initial migration

Revision ID: ecad0f2362a1
Revises: 
Create Date: 2025-09-05 22:54:34.458618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecad0f2362a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ssapId', sa.String(length=120), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('fundCode', sa.String(length=50), nullable=True),
    sa.Column('title0', sa.String(length=255), nullable=True),
    sa.Column('status', sa.DateTime(), nullable=True),
    sa.Column('contractNumber', sa.String(length=100), nullable=True),
    sa.Column('supplierCode', sa.String(length=100), nullable=True),
    sa.Column('supplierName', sa.String(length=255), nullable=True),
    sa.Column('trls', sa.String(length=100), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('yearAchievement', sa.Integer(), nullable=True),
    sa.Column('submissionDate', sa.DateTime(), nullable=True),
    sa.Column('submittedBy', sa.String(length=120), nullable=True),
    sa.Column('lastAuthor', sa.String(length=120), nullable=True),
    sa.Column('scheme', sa.String(length=255), nullable=True),
    sa.Column('arap_PlannedStartTRL', sa.String(length=50), nullable=True),
    sa.Column('arap_PlannedEndTRL', sa.String(length=50), nullable=True),
    sa.Column('arap_Description', sa.Text(), nullable=True),
    sa.Column('arap_StartofActivity', sa.String(length=100), nullable=True),
    sa.Column('arap_EED', sa.String(length=100), nullable=True),
    sa.Column('arap_ProspectforUse', sa.Text(), nullable=True),
    sa.Column('arap_PerformanceofCompagny', sa.Text(), nullable=True),
    sa.Column('arap_Note', sa.Text(), nullable=True),
    sa.Column('arap_OverallAmount', sa.String(length=100), nullable=True),
    sa.Column('arap_lastModifiedOn', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author0', sa.String(length=120), nullable=True),
    sa.Column('esaInternal', sa.Boolean(), nullable=True),
    sa.Column('technicalOfficer', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssapId')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ssapId', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('fundCode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.DateTime(), nullable=True),
    sa.Column('pptReport', sa.String(length=255), nullable=True),
    sa.Column('numberOfActivities', sa.Integer(), nullable=True),
    sa.Column('supplierCode', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('compLogo', sa.String(length=255), nullable=True),
    sa.Column('trls', sa.String(length=100), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('yearAchievement', sa.Integer(), nullable=True),
    sa.Column('submissionDate', sa.DateTime(), nullable=True),
    sa.Column('submittedBy', sa.String(length=120), nullable=True),
    sa.Column('lastAuthor', sa.String(length=120), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=True),
    sa.Column('storyDescription', sa.Text(), nullable=True),
    sa.Column('storyAuthor', sa.String(length=120), nullable=True),
    sa.Column('esaInternal', sa.Boolean(), nullable=True),
    sa.Column('storyStatus', sa.String(length=120), nullable=True),
    sa.Column('impact1', sa.String(length=255), nullable=True),
    sa.Column('impact2', sa.String(length=255), nullable=True),
    sa.Column('impact3', sa.String(length=255), nullable=True),
    sa.Column('contractNumber1', sa.String(length=100), nullable=True),
    sa.Column('contractNumber2', sa.String(length=100), nullable=True),
    sa.Column('contractNumber3', sa.String(length=100), nullable=True),
    sa.Column('contractNumber4', sa.String(length=100), nullable=True),
    sa.Column('contractNumber5', sa.String(length=100), nullable=True),
    sa.Column('customers', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssapId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    op.drop_table('activities')
    # ### end Alembic commands ###
